### PR TITLE
Update CMAKE minimum version to 2.8.12

### PR DESCRIPTION
**Pull request by smburdick**
To remove the CMAKE build [deprecation warning](https://github.com/greatscottgadgets/hackrf/issues/831), update the minimum required version.

### CODE REVIEW

**Comment by miek** [comment]
Could this be updated to 2.8.12 as the warning suggests, or is there a reason why it should be updated to a higher version?

**Comment by smburdick** [comment]
> Could this be updated to 2.8.12 as the warning suggests, or is there a reason why it should be updated to a higher version?

It could. I had no reason to make it that specific version. I can retry with 2.8.12.

**Comment by martinling** [comment]
The minimum supported version has been bumped again, so we now get:

```
 CMake Deprecation Warning at libhackrf/CMakeLists.txt:24 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of CMake.
```

I guess we can probably bump to 3.5 at this point (released 2016).

**Comment by mossmann** [comment]
I think 2.8.12 is good enough for today's release. Thank you for the contribution!

**Pull request merged**
