### PR TITLE
Cleanup of host software CMake build system

### LINKED ISSUE #360: hackrf host 2017.02.1 FreeBSD build problem (fftw3f)
Hey :-) I maintain FreeBSD port of HackRF.. I found a `fftw3f` build related problem in 2017.02.1 release host.. the library is found but the build fails.. looks like some CMake related problem..? Please advise :-)

### Steps to reproduce
See Output section at the end..

### Expected behaviour
Build ends without `fftw3f` related problems.

### Actual behaviour
```
Scanning dependencies of target hackrf_debug
[ 31%] Building C object hackrf-tools/src/CMakeFiles/hackrf_debug.dir/hackrf_debug.c.o
[ 37%] Linking C executable hackrf_debug
/usr/bin/ld: cannot find -lfftw3f
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1
```

### Version information
**Operating system**:
```
% uname -a
FreeBSD 0xCFF9 11.0-RELEASE-p8 FreeBSD 11.0-RELEASE-p8 #0: Wed Feb 22 06:12:04 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

**hackrf_info output:**
does not build

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.
```
% ls -al /usr/local/lib/libfftw3f*
-rw-r--r--  1 root  wheel  2854504 Feb 25 02:35 /usr/local/lib/libfftw3f.a
lrwxr-xr-x  1 root  wheel       18 Feb 25 02:35 /usr/local/lib/libfftw3f.so -> libfftw3f.so.3.5.5
lrwxr-xr-x  1 root  wheel       18 Feb 25 02:35 /usr/local/lib/libfftw3f.so.3 -> libfftw3f.so.3.5.5
-rwxr-xr-x  1 root  wheel  1519864 Feb 25 02:35 /usr/local/lib/libfftw3f.so.3.5.5
-rw-r--r--  1 root  wheel    41784 Feb 25 02:35 /usr/local/lib/libfftw3f_threads.a
lrwxr-xr-x  1 root  wheel       26 Feb 25 02:35 /usr/local/lib/libfftw3f_threads.so -> libfftw3f_threads.so.3.5.5
lrwxr-xr-x  1 root  wheel       26 Feb 25 02:35 /usr/local/lib/libfftw3f_threads.so.3 -> libfftw3f_threads.so.3.5.5
-rwxr-xr-x  1 root  wheel    25000 Feb 25 02:35 /usr/local/lib/libfftw3f_threads.so.3.5.5


% pkg info fftw3-float
fftw3-float-3.3.5
Name           : fftw3-float
Version        : 3.3.5
Installed on   : Sat Mar 18 23:06:44 2017 CET
Origin         : math/fftw3-float
Architecture   : freebsd:11:x86:64
Prefix         : /usr/local
Categories     : math
Licenses       : GPLv2
Maintainer     : jhale@FreeBSD.org
WWW            : http://www.fftw.org/
Comment        : Fast Discrete Fourier Transform (Single Precision C Routines)
Options        :
	G77_WRAPPERS   : off
	OPENMP         : off
	OPENMPI        : off
	OPTIMIZED_CFLAGS: on
	SIMD           : on
Shared Libs provided:
	libfftw3f.so.3
	libfftw3f_threads.so.3
Annotations    :
	repo_type      : binary
	repository     : FreeBSD
Flat size      : 4.30MiB
Description    :
FFTW is a C subroutine library for computing the Discrete Fourier Transform
(DFT) in one or more dimensions, of both real and complex data, and of
arbitrary input size. We believe that FFTW, which is free software, should
become the FFT library of choice for most applications. Our benchmarks,
performed on a variety of platforms, show that FFTW's performance is
typically superior to that of other publicly available FFT software.
Moreover, FFTW's performance is portable: the program will perform well on
most architectures without modification.

The FFTW package was developed at MIT by Matteo Frigo and Steven G.
Johnson.  Please send email to fftw@theory.lcs.mit.edu so that we can keep
track of users and send you information about new releases.  The latest
version of FFTW, benchmarks, links, and other information can be found at
the FFTW home page.

WWW: http://www.fftw.org/
```

### Output
```
% tar -xxf hackrf-2017.02.1.tar.xz 
% ls
hackrf-2017.02.1	hackrf-2017.02.1.tar.xz
% cd hackrf-2017.02.1
% ls
COPYING		Readme.md	doc		firmware-bin	host
RELEASENOTES	TRADEMARK	firmware	hardware
% cd host/
% mkdir build
% cd build/
% cmake ..
-- The C compiler identification is Clang 3.8.0
-- The CXX compiler identification is Clang 3.8.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/CC
-- Check for working CXX compiler: /usr/bin/CC -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "1.3.0") 
-- Checking for module 'libusb-1.0'
--   Found libusb-1.0, version 1.0.13
-- Found LIBUSB: /usr/lib/libusb.so  
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Checking for module 'fftw3f'
--   Found fftw3f, version 3.3.5
-- Configuring done
-- Generating done
-- Build files have been written to: (..)/hackrf/release/hackrf-2017.02.1/host/build
% make
Scanning dependencies of target hackrf-static
[  6%] Building C object libhackrf/src/CMakeFiles/hackrf-static.dir/hackrf.c.o
[ 12%] Linking C static library libhackrf.a
[ 12%] Built target hackrf-static
Scanning dependencies of target hackrf
[ 18%] Building C object libhackrf/src/CMakeFiles/hackrf.dir/hackrf.c.o
[ 25%] Linking C shared library libhackrf.so
[ 25%] Built target hackrf
Scanning dependencies of target hackrf_debug
[ 31%] Building C object hackrf-tools/src/CMakeFiles/hackrf_debug.dir/hackrf_debug.c.o
[ 37%] Linking C executable hackrf_debug
/usr/bin/ld: cannot find -lfftw3f
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

 % grep fftw3f *
CMakeCache.txt:FFTW_LDFLAGS:INTERNAL=-L/usr/local/lib;-lfftw3f
CMakeCache.txt:FFTW_LIBRARIES:INTERNAL=fftw3f
CMakeCache.txt:FFTW_STATIC_LDFLAGS:INTERNAL=-L/usr/local/lib;-lfftw3f;-lm
CMakeCache.txt:FFTW_STATIC_LIBRARIES:INTERNAL=fftw3f;m
CMakeCache.txt:FFTW_fftw3f_INCLUDEDIR:INTERNAL=
CMakeCache.txt:FFTW_fftw3f_LIBDIR:INTERNAL=
CMakeCache.txt:FFTW_fftw3f_PREFIX:INTERNAL=
CMakeCache.txt:FFTW_fftw3f_VERSION:INTERNAL=

% uname -a
FreeBSD 0xCFF9 11.0-RELEASE-p8 FreeBSD 11.0-RELEASE-p8 #0: Wed Feb 22 06:12:04 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

### PR DESCRIPTION
**Pull request by multiplemonomials**
Hi all!  Recently we got a HackRF at my lab (USC RPL), and while we're having a really fun time playing around with it, we did have a few issues at the start getting the host software set up -- especially on Windows with MSVC.  It wasn't anything we couldn't deal with, but I did see a few places where the CMake build system could be improved, so I thought I'd try to clean it up a bit.  I incorporated a few bits and pieces from other projects I've worked on (mainly LibraryUtils.cmake, and a much less sophisticated version of FindFFTW), but also wrote a fair amount of new logic from scratch.  Hopefully the build system should run a bit smoother now!

There are a lot of small changes as you can see, but I'll try to list the major things here:
- Clean up and consolidate logic that was split across multiple build files into a single clean block at the top level
  - Compile flags
  - Dependencies
  - Uninstall logic
- Rewrite FindFFTW based on my earlier version.  It's now smart enough to consider libfftw3 vs libfftw3f (as well as all the other fftw3 libraries) as separate components, and to generate good, clear error messages if one of them is missing.
  - Should fix #360
- Clean up FindUSB and FindHACKRF according to CMake find module best practices.  
  - Hopefully the issues where the configuration continues even though libusb was not found (which should have been a fatal error) should stop now!
- Add a proper find module for libm
- Set up hackrf DLL export / import logic to be automatically managed by CMake.  

Hope all this stuff seems useful!  As you can see from the build instructions, it makes the Windows build quite a bit simpler because it enables all libraries to be found correctly just by setting the prefix path to where the libraries are installed.  Hopefully it should improve life on other platforms too.

I'm happy to answer any other questions or make any other changes you need, just let me know.

### CODE REVIEW

**Comment by multiplemonomials** [comment]
Is this going to be looked at?

**Comment by straithe** [comment]
This has been looked at internally, but there are some conflicts with the existing repository that need to be addressed. We've been discussing how we would like to update this so there are no conflicts. 

We do really appreciate that you have submitted this PR and we are interested in accepting it. Thank you for checking in.

**Comment by multiplemonomials** [comment]
Good to hear!  I went ahead and rebased it.

**Comment by straithe** [comment]
Thank you! I really appreciate it.

**Comment by multiplemonomials** [comment]
Actually I looked over the code again and realized that FindFFTW was quite out of date from the "upstream" version (I originally made it for the Amber MD project).  So, I copied in the new version, as well as another really useful module it uses, TryLinkLibraries, which is used to make sure that libraries found by CMake are properly linkable.

**Comment by straithe** [comment]
Thanks for the updates! We ran our CI and there was a CMake error on Ubuntu. Would you please dig into that and address that issue?

**Comment by multiplemonomials** [comment]
Oops missed a
```
include(CMakePushCheckState)
```

**Comment by straithe** [comment]
Thank you for the code updates!  Your PR passes all the preliminary checks. I'll make sure the reviewing team takes a look when they can.

**Comment by straithe** [comment]
Thank you very much for this PR!

**Comment by mossmann** [comment]
We decided to revert this PR after discovering a couple problems:

1. This broke the ability to build at the subdirectory level (`libhackrf` or `hackrf-tools`) in addition to the top (`host`) level (discovered in #1007). We require this ability in order to support distributions that package the library and the command-line tools separately.

2. This changed the `libhackrf.so` versioning from MAJOR.MINOR.PATCH to MAJOR.MINOR which can cause some installation problems if people `make install` both before and after the PR is merged. We're not sure, but this might also be troublesome for distro packagers, so we think it would be safest to continue using MAJOR.MINOR.PATCH.

The second problem looks like it could be fixed easily, but the first one appears to be more difficult and is a more significant problem.

**Comment by martinling** [comment]
> 2\. This changed the `libhackrf.so` versioning from MAJOR.MINOR.PATCH to MAJOR.MINOR which can cause some installation problems if people `make install` both before and after the PR is merged.

To give the specifics of this problem - this was the result after `make install` on my development system, when working on my branch for  #982 after merging in these changes:

```
$ ls -l /usr/local/lib/libhackrf.*
-rw-r--r-- 1 root staff  33388 Dec  7 23:56 /usr/local/lib/libhackrf.a
lrwxrwxrwx 1 root staff     14 Nov  3 18:01 /usr/local/lib/libhackrf.so -> libhackrf.so.0
lrwxrwxrwx 1 root staff     18 Dec  8 22:22 /usr/local/lib/libhackrf.so.0 -> libhackrf.so.0.7.0
-rw-r--r-- 1 root staff  42496 Dec  7 23:53 /usr/local/lib/libhackrf.so.0.6
-rw-r--r-- 1 root staff  42496 Dec  7 23:56 /usr/local/lib/libhackrf.so.0.6.0
-rw-r--r-- 1 root staff 129696 Dec  8 22:22 /usr/local/lib/libhackrf.so.0.7
-rw-r--r-- 1 root staff  42648 Dec  3 18:40 /usr/local/lib/libhackrf.so.0.7.0
```

The modifiied build system installed `libhackrf.so.0.7`, but left `libhackrf.so.0` symlinked to a `libhackrf.so.0.7.0` from several days before, so the `make install` did not actually cause the version in use to change. This caused a lot of confusion when trying to debug why my changes weren't working!

**Comment by multiplemonomials** [comment]
Ok I'll work on fixing these issues.
One thing I just realized is, would it be OK if, to build only the library or the applications, you had to run _cmake_ at the top level directory but then only run _make_ in a subdirectory?  e.g. 
````
cd host
mkdir build && cd build
cmake ..
cd libhackrf
make -j4 && sudo make install
```
If that's OK then the build system actually already supported this feature.

**Comment by martinling** [comment]
> would it be OK if, to build only the library or the applications, you had to run _cmake_ at the top level directory but then only run _make_ in a subdirectory?

It's not just about our own preference. At this point, there are quite a few distributions out there which will already have packaging set up to work with the build system as it was before - as well as any number of scripts etc that users may have set up privately.

I think we should avoid doing anything that will require changes to existing workflows, unless there's a really strong reason.

**Pull request merged**
