### PR TITLE
Move RF section around to add protection

### PR DESCRIPTION
**Pull request by cjheath**
I know you suggested which branch I should do this to (not master) but I kinda... got started, and ended up here. This was a learning experience with Kicad for me, and though there's five hours work in it, I'll do it again if there's no way to integrate it. Your call...

There should now be ample room in the RF section to add both the back-to-back diodes SMP1330 to protect the LNA, and also to add a Vaa/GND voltage divider to centre protection of the main antenna (clamping at +-2.3V).

### CODE REVIEW

**Comment by cjheath** [comment]
To save you the trouble of fetching the repo and opening the files, here are screenshots of the schematic changes:
hackrf-protected-rf-section-sch

and the PCB:

hackrf-protected-rf-section-pcb

**Comment by cjheath** [comment]
Note that this layout was an experiment only. It does not represent proper RF layout practices. (Neither does much of the existing board OTOH). I will do it properly next time - this was just to get familiar with Kicad (previously an Eagle user - yuk!)

**Comment by cjheath** [comment]
@mossmann can you please comment? I'd like to know whether you would incorporate a version of this, and which branch I should add it to, to make it convenient for you to merge.

**Comment by cjheath** [comment]
Hello? Anyone home?

**Comment by cjheath** [comment]
Still no response. Not good, for a project that advertises itself as "open source".

**Comment by virendera** [comment]
@cjheath may I ask sometimes from you if you allows me, basically my question is not related to this thread but with hackrf.

**Comment by cjheath** [comment]
@virendera My email address is in my Github profile, you don't need to message me here.

**Comment by HenrikBork** [comment]
Q1: Why did you choose not to protect the "LNA bypass" signal path?
Q2: Did you put further work into this?

I agree pretty much with all your points, and i do not get why @mossmann is not more cooperative - but i guess hi is busy designing a "HackRF Two" or whatever :-)

BTW: i just zapped my brand new HackRF One in by own quick antenna comparison test :-(

**Comment by cjheath** [comment]
@HenrikBork Sorry to hear you zapped your HackRF One. I found replacement devices cheaply at AliExpress, and even if you can't solder it yourself, a phone repair place should be able to do it for you. I don't understand why @mossmann thinks it's ok to allow this to happen to so many customers either. It seems irresponsible and bad business practise to me, but perhaps he has some rationale. FWIW, the new device he's chosen to replace the MGA-81653 is a different technology, but he disbelieves the data sheets which indicate that it is *even more* sensitive to damage.

A1: The SMP1330 clamp to the GND, VAA rails should protect everything else (esp the Tx amp), as far as I have checked. The TVS does literally *nothing* useful, it will only clamp after everything else is ash. The pHEMT gate of the MGA-81653 requires better protection, so it has a bi-directional clamp to ground.

A2: I have offered to help a clone manufacturer get started making an improved version. It seems unfortunate that a project into which so much work has gone should need to be forked, but I'll help make that happen if @mossmann continues to stone-wall me.

I am still willing to re-do the design and layout changes using his latest version, as long as he agrees to support me in the effort and to seriously consider incorporating them (this is not a new offer, it's been open since the start). As it is I spent several full days work and have had *no response*. Odd behaviour, it seems.

**Comment by HenrikBork** [comment]
Argh! i put all my focus on D20, and overlooked D21... Sorry :-)
Did you try out your circuit and what are you experience / expectations regarding signal loss/reduction?

Regarding my "ZappRF One": i already ordered the MGA's and a few SMP1330. But since the MGA-81563 are obsolete we need to find another part in the future - do you have any suggestions? (Broadcom seems to be shutting down their discrete LNA sales)

**Comment by cjheath** [comment]
@HenrikBork I have added only D20 to my repaired HackRF, I have not manufactured a whole new board with the revised layout shown. The D20 I added is upside-down at an angle on top of my LNA's input pin, with one of the earthy pins soldered down and one dangling in the air and grounded by 3mm of wire. So I have various odd impedances and resonators that will affect performance, but I don't have the equipment to measure that.

You can see the two SMP1330 on the PCB layout snapshot above. D21 is right in the centre with the signal trace running between its legs (see how the trace is thinned as it approaches the pad?). D20's signal leg is right in the centre-top of the image and also has the trace thinning (this compensates for the pad capacitance). The effect of this trace thinning and pad capacitance is to produce an LCL T-filter with a cutoff usually around 10GHz. This can be calculated/simulated  for high-performance apps (using a field solver), but the PCB material must be known. So it's just an approximation/guesstimate as it stands. I learned this approach from (and had it scrutinised by) a guy who has patents on techniques he used in piece of >$1M test equipment he designed over 20 years ago - which was fully simulated and tested at that time - I trust his advice!

The SMP1330 data sheet is a little difficult to simulate because they're non-linear, but with the optimised layout it should introduce very little loss or intermodulation below 2GHz, and not much above that. The PIN diodes are very low-capacitance below their threshold, but the capacitance increases rapidly as threshold is approached (and they start to become conductive also). So the distortion (intermodulation) will depend on signal level. At sub-1dBm levels they're effectively absent, and below threshold at sub-1GHz frequencies they are completely unobtrusive.

**Comment by cjheath** [comment]
> Regarding my "ZappRF One": i already ordered the MGA's and a few SMP1330. But since the MGA-81563 are obsolete we need to find another part in the future - do you have any suggestions? (Broadcom seems to be shutting down their discrete LNA sales)

@mossman had mentioned he plans to use TRF37D73. It has a 10dBm maximum input power compared to the MGA's max of 13dBm (note the failure mode is voltage, not power, and the MGA's limits are assymetric whereas the TRF is more symmetric). The SMP1330 clamping is also mostly voltage-based too, not power; about one diode drop or 0.7V. It should provide substantial (if not total) protection of either device.

**Comment by deathzombee** [comment]
Have you had any communication with @mossmann? It seems odd to leave a pull for so long without making a decision on it. If its not going to be approved you would think it would closed by now.

**Comment by cjheath** [comment]
> Have you had any communication with @mossmann?

Odd perhaps, but no further communication since he closed the original issue. He seems to have recently started work on h1r6, which has some similar changes (updating parts), and some divergent ones, so it seems that the project may have been forked, as with each step it is unfortunately becoming harder to merge the two versions. I did not want to maintain a fork, but to contribute to the original version.

Interesting that you asked this today. I have just this afternoon resolved a production problem that was preventing the revised version being made available for purchase.

**Comment by ur7idr** [comment]
> To save you the trouble of fetching the repo and opening the files, here are screenshots of the schematic changes (edited to show the revised layout in below commits):
> hackrf-protected-rf-section-sch
> 
> and the PCB:
> 
> hackrf-protected-rf-section-pcb

Dear cjheath,

what is the name of TVS diode connected directly to antenna input? 

Thanks!

**Comment by cjheath** [comment]
@mossmann used LXES15AAA1-100, a 15V TVS (also on CLKIN&CLKOUT). You don't need it, it cannot help anything. I removed it from the current revision and used Skyworks limiter diodes that have a radical clamping action at 0.7V, which are designed specifically for this application. The sudden impedance change when they clamp reflects up to 100W of RF energy back to the source, even though the diodes themselves can only sink 1W (briefly). I used BAS70 diode pairs to protect CLKIN/CLKOUT.

**Comment by berkinkartal** [comment]
@cjheath any updates on this? I'd love to obtain an update version of your pcb and schematic design...
@mossmann I just zapped my TX AMP - FYI :) In case you enjoy reading these...

**Comment by cjheath** [comment]
> @cjheath any updates on this? I'd love to obtain an update version of your pcb and schematic design...

@berkinkartal My revised version is selling like hot cakes (no benefit to me) at AliExpress: https://hackrf.aliexpress.com/store/group/HackRF-One/4652072_514458823.html
Last I heard almost all of the first batch of 1000 was sold. I'm getting thankyous from happy buyers. Apparently the Tx power is slightly increased over the version using the old MGA MMIC.

> @mossmann I just zapped my TX AMP - FYI :) In case you enjoy reading these...

I think he still has his ears wide shut. Pity.

**Comment by Notupus** [comment]
> 
> 
> > @cjheath any updates on this? I'd love to obtain an update version of your pcb and schematic design...
> 
> @berkinkartal My revised version is selling like hot cakes (no benefit to me) at AliExpress: https://hackrf.aliexpress.com/store/group/HackRF-One/4652072_514458823.html
> Last I heard almost all of the first batch of 1000 was sold. These folk were selling about 700/month, but I expect that will pick up now. I'm getting thankyous from happy buyers.
> Reports say the Tx power is slightly increased over the version using the old MGA MMIC.
> 
> > @mossmann I just zapped my TX AMP - FYI :) In case you enjoy reading these...
> 
> I think he still has his ears wide shut. Pity.

Do they still make the revised non zappable version?

**Comment by cjheath** [comment]
There is still some stock, but production is suspended at present due to the chip shortage/high price.
At least one of the advertisements has been taken down, so write and ask them.

**Comment by mossmann** [comment]
We've tested this design and found that it degrades performance unacceptably: https://greatscottgadgets.com/2021/12-07-testing-a-hackrf-clone/

The supposed protection benefits remain unproven.

**Pull request closed without merging**
