### PR TITLE
hackrf_biast - (temporarily) enable antenna power from the command line

### PR DESCRIPTION
**Pull request by ai6aj**
Adds a simple utility, hackrf_biast, to enable the antenna power from the command line for use with software such as SDR# which only has the bare minimum support for HackRF.  Addresses issues #1309 and #1311

Caveat: the antenna power will turn off once RX is stopped

### CODE REVIEW

**Comment by ai6aj** [comment]
#1309

**Comment by martinling** [comment]
Having it only work the first time you start RX isn't really a solution. I think that if we merge this we will just get a lot of bug reports saying it doesn't work properly.

If we're going to have utilities that override HackRF settings, to work around issues in closed source software, then that really needs firmware support so that the forced settings can be made persistent.

It would be a lot simpler for everyone if SDR# would just add a control for the bias tee.

**Comment by ai6aj** [comment]
> If we're going to have utilities that override HackRF settings, to work around issues in closed source software, then that really needs firmware support so that the forced settings can be made persistent.

Agreed.  It's been a few years since I hacked on the firmware but I don't think it's particularly difficult.  I'll

**Comment by martinling** [comment]
If you want to work on the firmware support that'd be great. I've added some thoughts on how this could work [here](https://github.com/greatscottgadgets/hackrf/issues/1309#issuecomment-1521504784).

**Pull request closed without merging**
