### PR TITLE
Fixes for concurrency bugs in start/stop operations

### PR DESCRIPTION
**Pull request by martinling**
Fixes bug #916.

Previously, there was a race which could lead to a transfer being left active after `cancel_transfers()` completed. This would then cause the next `prepare_transfers()` call to fail, because `libusb_submit_transfer()` would return an error due to the transfer already being in use.

The sequence of events that could cause this was:

1. Main thread calls `hackrf_stop_rx()`, which calls `cancel_transfers()`, which iterates through the 4 transfers in use and cancels them one by one with `libusb_cancel_transfer()`.
1. During this time, a transfer is completed. The transfer thread calls `hackrf_libusb_transfer_callback()`, which handles the data and then calls `libusb_submit_transfer()` to resubmit that transfer.
1. Now, `cancel_transfers()` and `hackrf_stop_rx()` are completed but one transfer is still active.
1. The next `hackrf_start_rx()` call fails, because `prepare_transfers()` tries to submit a transfer which is already in use.

To fix this, we add a lock which must be held to either cancel transfers or restart them. This ensures that only one of these actions can happen for a given transfer; it's no longer possible for a transfer to be cancelled and then immediately restarted.

With this change, I can now run the test program from #916 without failures.

### CODE REVIEW

**Comment by martinling** [comment]
I've added a second commit to fix an orthogonal but closely related issue.

After cancelling transfers, we need to wait for all cancellation handling to complete before trying to do anything new with the same transfers.
    
Calling `libusb_cancel_transfer()` only starts the cancellation of a transfer. The process is not complete until the transfer callback has been called with status `LIBUSB_TRANSFER_CANCELLED`.

If `hackrf_start_rx()` is called soon after `hackrf_stop_rx()`, `prepare_transfers()` may be called before the previous cancellations are completed, resulting in a `LIBUSB_ERROR_BUSY` when a transfer is reused with `libusb_submit_transfer()`.
    
To prevent this happening, I've made the transfer thread keep track of which transfers have finished (either by completion, or cancellation), and made `cancel_transfers()` wait until all transfers are finished before returning.
    
This is implemented using a pthread condition variable which is signalled from the transfer thread and waited on by `cancel_transfers()`.

With this change, I can no longer reproduce the failure to restart RX seen in #883.

**Comment by martinling** [comment]
There's a recent [thread](https://lists.osmocom.org/hyperkitty/list/osmocom-sdr@lists.osmocom.org/thread/7TKOAOP5KNQBBCDJRV7EI67AFKEDTNCP/) on the osmocom-sdr list from Jasper van den Eshof, who has been fixing more or less exactly the same issue in librtlsdr.

Looking at the [librtlsdr code](https://github.com/steve-m/librtlsdr/blob/master/src/librtlsdr.c) suggests a simpler approach that could be used to orchestrate the cancellations, which would eliminate the need for the locking introduced in https://github.com/greatscottgadgets/hackrf/pull/1029/commits/b346790e2da866fd79e41393f3ddf2db6eb25102.

- In `hackrf_stop_{rx|tx}()`, set a flag to request cancellation, then call `libusb_interrupt_event_handler()`.
- In `transfer_threadproc`, use `libusb_handle_events_timeout_completed()` instead of `libusb_handle_events_timeout()`, and pass the flag set in `hackrf_stop_{rx|tx}` as the `completed` argument. This function will then return when requested.
- Once `libusb_handle_events_timeout_completed()` has completed, do the `cancel_transfers()` work in the transfer thread. The mutex between `cancel_transfers()` and `hackrf_libusb_transfer_callback()` would then not be necessary.
- After cancelling transfers, loop on `libusb_handle_events_timeout_completed()` until all cancellation callbacks have completed. Then signal `hackrf_stop_{rx|tx}` as before.

**Comment by martinling** [comment]
Another useful observation from the discussion with Jasper - the individual `transfer_finished` flags, added in my second commit, could be more simply replaced with a count of active transfers, which is incremented on submission and decremented on completion or cancellation.

I'll work on making both improvements.

**Comment by martinling** [comment]
I've added a third commit which fixes the firmware-side issue #1042.

With the combination of all three changes on this PR, I can no longer reproduce any problems with repeated start/stop of HackRF.

I plan to do some further work to simplify the solutions, but for anyone having problems this branch should work as-is.

**Comment by gozu42** [comment]
can confirm no longer seeing any restart-hangs with 7057235a on pc+raspi with test app from https://github.com/greatscottgadgets/hackrf/issues/916 or gqrx ctrl-d stresstest.

**Comment by martinling** [comment]
Since this PR has been tested & confirmed to fix #883, #916 and #1042, I propose we get it merged as-is without further changes, and we can look at making the simplifications discussed in [this comment](https://github.com/greatscottgadgets/hackrf/pull/1029#issuecomment-1017639509) and [this comment](https://github.com/greatscottgadgets/hackrf/pull/1029#issuecomment-1019592611) in a separate PR later.

**Comment by mossmann** [comment]
Outstanding troubleshooting and solutions!

**Comment by martinling** [comment]
The simplification discussed in [this comment](https://github.com/greatscottgadgets/hackrf/pull/1029#issuecomment-1019592611) is now in PR #1071.

I had a go at the the other proposed change outlined in [this comment](https://github.com/greatscottgadgets/hackrf/pull/1029#issuecomment-1017639509), but decided not to go ahead with it. Although it would eliminate some locking, it would just add different complications instead. It would detract from the simplicity of the transfer thread, which is currently just a trivial libusb event handling loop.

**Pull request merged**
